name: First Workflow
on: [clone]
jobs:
  runs-shell-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-step
        run: echo "Hello"
      - name: run-multiple-step
        run: |
          mvn -v
          java --version
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-windows-commands-job:
    runs-on: windows-latest
    needs: [runs-shell-command-job]
    steps:
        - name: Directory Powershell
          run: Get-Location
        - name: Directory Bash
          run: pwd
          shell: bash

          
